AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'data-storage

  Sample SAM Template for data-storage

  '
    
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs12.x
    CodeUri: samplesProject/  
Resources:
  #------------------------API-------------
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: sampleGwApiCloudForm
      StageName: dev
      Variables:
        DB_ENV: dev
  qaStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ServerlessRestApiDeploymentQa
      RestApiId: !Ref BasicAWSApiGateway
      StageName: qa
      Variables:
        DB_ENV: qa
  ServerlessRestApiDeploymentQa:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref BasicAWSApiGateway
      Description: 'RestApi deployment for QA'
  #-----------------------FUNCTIONS----------------    
  ##----------------------GET TOKEN----------------
  getTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: data-storage-users
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey    
      Handler: getToken.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /token
            Method: post
  ##-----------------------GET ALL SAMPLES-----------          
  getAllSamplesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: dev_samples
        - DynamoDBReadPolicy:
            TableName: qa_samples   
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey        
      Handler: getAllSamples.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples
            Method: get
  ##-------------------------GET SAMPLE BY ID------------
  getSampleByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: dev_samples
        - DynamoDBReadPolicy:
            TableName: qa_samples   
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey        
      Handler: getSampleById.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples/{id}
            Method: get
  ##-------------------------DELEET SAMPLE BY ID-------------
  deleteSampleByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: dev_samples
        - DynamoDBCrudPolicy:
            TableName: qa_samples    
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey       
      Handler: deleteSampleById.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples/{id}
            Method: delete
  ##-------------------------PUT SAMPLE-------------------------
  putSampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: dev_samples
        - DynamoDBCrudPolicy:
            TableName: qa_samples  
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey         
      Handler: putSample.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples/{id}
            Method: put           
  ##-------------------------PATCH SAMPLE BY ID------------------           
  patchSampleByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: dev_samples
        - DynamoDBCrudPolicy:
            TableName: qa_samples  
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey         
      Handler: patchSampleById.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples/{id}
            Method: patch
  ##------------------------USE SAMPLE BY ID-----------------------
  useSampleByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: dev_samples
        - DynamoDBCrudPolicy:
            TableName: qa_samples   
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey        
      Handler: useSampleById.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /samples/{id}/use
            Method: get            
  ##-------------------------RENDER HTML-----------------------------
  renderHtmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: dev_samples
        - DynamoDBCrudPolicy:
            TableName: qa_samples   
        - SSMParameterReadPolicy:
            ParameterName: jwtsecretkey        
      Handler: renderHtml.handler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /
            Method: get                        